In [1]:
import numpy as np

### In this Notebook I have covered 
* Generate arrays of random numbers
* Change shape of arrays
* Stack arrays
* Combine arrays
* newaxis
* Shallo Copy / Deep Copy

### Generate arrays of random numbers

In [2]:
# generate array of random values
np.random.random(size=(3,2))

array([[0.57930957, 0.49066128],
       [0.81111731, 0.09414301],
       [0.06849228, 0.67329027]])

In [3]:
# generate array of integers between a range of values
np.random.randint(low=2, high=10, size=(3,3))

array([[7, 8, 3],
       [7, 2, 6],
       [5, 9, 9]])

### Change shape of arrays

In [6]:
# Change shape of an array

arr = np.array([[3,4,5,6],[4,6,7,2],[8,9,5,4]])
print(arr)

[[3 4 5 6]
 [4 6 7 2]
 [8 9 5 4]]


In [7]:
# Change shape using reshape
arr.reshape(2,6)

array([[3, 4, 5, 6, 4, 6],
       [7, 2, 8, 9, 5, 4]])

In [8]:
# Change shape using Transpose
arr.T

array([[3, 4, 8],
       [4, 6, 9],
       [5, 7, 5],
       [6, 2, 4]])

In [9]:
# flatten array
arr.ravel()

array([3, 4, 5, 6, 4, 6, 7, 2, 8, 9, 5, 4])

In [10]:
# modify original array using resize()
arr.resize(6,2)
arr

array([[3, 4],
       [5, 6],
       [4, 6],
       [7, 2],
       [8, 9],
       [5, 4]])

### Stack arrays

In [11]:
a = np.random.randint(low=1, high=9, size=(3,4))
a

array([[1, 6, 4, 8],
       [7, 8, 4, 4],
       [4, 8, 3, 1]])

In [12]:
b = np.random.randint(low=1, high=9, size=(2,4))
b

array([[3, 3, 5, 3],
       [3, 6, 3, 2]])

### Vertical Stack

In [13]:
# Stack arrays in sequence vertically
np.vstack((a, b))

array([[1, 6, 4, 8],
       [7, 8, 4, 4],
       [4, 8, 3, 1],
       [3, 3, 5, 3],
       [3, 6, 3, 2]])

### Horizontal Stack

In [14]:
a = np.array(([2,3,4], [4,5,6]))
b = np.array([[11,12],[13,14]])


In [15]:
a

array([[2, 3, 4],
       [4, 5, 6]])

In [16]:
b

array([[11, 12],
       [13, 14]])

In [17]:
np.hstack((a, b))

array([[ 2,  3,  4, 11, 12],
       [ 4,  5,  6, 13, 14]])

### Combine 2D array and 1D array

In [18]:
A = np.array([[140, 40], [120, 20], [150,50]])
B = np.array(['M', 'S', 'T'])

In [19]:
A

array([[140,  40],
       [120,  20],
       [150,  50]])

In [20]:
B

array(['M', 'S', 'T'], dtype='<U1')

In [21]:
A.T

array([[140, 120, 150],
       [ 40,  20,  50]])

In [22]:
A_B = np.vstack((A.T, B)).T
A_B

array([['140', '40', 'M'],
       ['120', '20', 'S'],
       ['150', '50', 'T']], dtype='<U11')

### newaxis
* newaxis is also called as a pseudo-index that allows the temporary addition of an axis 
* Simply put, newaxis is used to increase the dimension of the existing array by one more dimension

In [23]:
from numpy import newaxis

In [24]:
a = np.array([1,2,3])
b= np.array([4,5,6])


In [25]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [26]:
a

array([1, 2, 3])

In [27]:
a.shape

(3,)

In [28]:
a[newaxis, :]

array([[1, 2, 3]])

In [29]:
a[newaxis, :].shape

(1, 3)

In [30]:
a[:, newaxis]

array([[1],
       [2],
       [3]])

In [31]:
a[:, newaxis].shape

(3, 1)

In [32]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
np.hstack((a[:, newaxis], b[:, newaxis])).T

array([[1, 2, 3],
       [4, 5, 6]])

### Asignment Vs Views (Shallow Copy) Vs Deepcopy

In [34]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Simple assignments make no copy of array objects or of their data.
b = a 
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
id(b) == id(a)

True

In [37]:
b[0]=100

In [38]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [39]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [40]:
b.resize(5,2)

In [41]:
b

array([[100,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

In [42]:
a

array([[100,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

In [43]:
a.resize(2,5)

In [44]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [45]:
b

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [46]:
# Python passes mutable objects as references, so function calls make no copy.
def f(x):
    print(id(x))

In [47]:
f(a)

2671798518768


In [48]:
id(a)

2671798518768

### Shallow Copy or Views
Views or shallow copy look at same underlying data

In [49]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [50]:
c = a.view()

In [51]:
id(c) == id(a)

False

In [52]:
c

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [53]:
c[0,0] = 500

In [54]:
c

array([[500,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [55]:
a

array([[500,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [56]:
a[1,1] = 600
a

array([[500,   1,   2,   3,   4],
       [  5, 600,   7,   8,   9]])

In [57]:
c

array([[500,   1,   2,   3,   4],
       [  5, 600,   7,   8,   9]])

In [58]:
# lets change shape
c.resize(5,2)

In [59]:
c

array([[500,   1],
       [  2,   3],
       [  4,   5],
       [600,   7],
       [  8,   9]])

In [60]:
a

array([[500,   1,   2,   3,   4],
       [  5, 600,   7,   8,   9]])

In [61]:
## Slicing also creates a view

a = np.array([[1,2,3],[4,5,6]])
c = a[:,]

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
c[0,0]=100
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [65]:
a

array([[100,   2,   3],
       [  4,   5,   6]])

### Deepcopy

In [66]:
a = np.arange(1,13).reshape(3,4)

In [67]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
b = a.copy()

In [69]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
id(a) == id(b)

False

In [76]:
b[0,0]=999
b

array([[999,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [77]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
b

array([[999,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])