### What is Numpy ?
- `Numpy` is a Python package which stands for 'Numerical Python'. 
- It is the core library for scientific computing

In [19]:
# load package
import numpy as np

In [22]:
np.__version__

'1.18.1'

### The N-dimensional array (ndarray): 
An ndarray is a (usually fixed-size) multidimensional array of items of the same type and size.

#### Create array

In [31]:
# runs scored by a batsman in 5 matches one-day series
runs = np.array([110, 80, 50, 20, 140])

In [32]:
# type of object
type(runs)

numpy.ndarray

In [33]:
# number of dimensions
runs.ndim

1

In [34]:
# to get number of elements in each dimension 
runs.shape

(5,)

In [46]:
# Number of elements in the array.
runs.size

5

#### numpy functions

In [25]:
# total runs in series by player
np.sum(runs)

400

In [26]:
np.cumsum(runs)

array([110, 190, 240, 260, 400], dtype=int32)

In [28]:
# min , max, average score in series

{'min_score:': np.min(runs), 
 'max_score': np.max(runs), 
 'series_avg': np.mean(runs)
}

{'min_score:': 20, 'max_score': 140, 'series_avg': 80.0}

In [43]:
# runs scored by player in a 5 matches test series 
test_runs = np.array([[80, 88], 
                      [90, 100], 
                      [40, 20], 
                      [80, 100], 
                      [200, 90]])

In [41]:
test_runs.ndim

2

In [42]:
# no. of elements in each dimension
test_runs.shape

(5, 2)

In [45]:
# no. of elements in array
test_runs.size

10

In [47]:
# Length of one array element in bytes.
test_runs.itemsize

4

In [48]:
# total bytes consumed by the elements of the array.
test_runs.nbytes

40

In [49]:
test_runs

array([[ 80,  88],
       [ 90, 100],
       [ 40,  20],
       [ 80, 100],
       [200,  90]])

In [50]:
# total runs scored player in test series
test_runs.sum()

888

In [52]:
# match-wise total runs scored in test series
test_runs.sum(axis=1)

array([168, 190,  60, 180, 290])

In [61]:
# average score of 1st vs 2nd innings
test_runs.mean(axis=0)

array([98. , 79.6])

#### indexing
**index starts from number 0**

In [62]:
test_runs

array([[ 80,  88],
       [ 90, 100],
       [ 40,  20],
       [ 80, 100],
       [200,  90]])

In [63]:
# runs scored in second test match
test_runs[1, :]

array([ 90, 100])

In [64]:
# runs scored in second innings of 4th and 5th test match
test_runs[[3,4], 1]

array([100,  90])

In [65]:
# runs scored in last innings of series
test_runs[-1, -1]

90

In [68]:
# standard deviation in first innings vs second innings
test_runs[:,0].std(), test_runs[:,1].std()

(53.81449618829484, 30.209932141598728)

In [69]:
# count number of centuries he scored
test_runs >=100

array([[False, False],
       [False,  True],
       [False, False],
       [False,  True],
       [ True, False]])

In [70]:
np.sum(test_runs >=100)

3

In [73]:
# how many centuries in first vs second innings
np.sum(test_runs[:, 0] >= 100)

1

In [74]:
np.sum(test_runs[:, 1] >= 100)

2

In [75]:
test_runs

array([[ 80,  88],
       [ 90, 100],
       [ 40,  20],
       [ 80, 100],
       [200,  90]])

In [78]:
# in which innings he scored max runs
test_runs.argmax(axis=0)

array([4, 1], dtype=int64)

In [81]:
np.info(test_runs)

class:  ndarray
shape:  (5, 2)
strides:  (8, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x223b42e03a0
byteorder:  little
byteswap:  False
type: int32
