### Numpy
* NumPy is a Python package, which stands for 'Numerical Python'.
* At the core of the NumPy package, is the ndarray object. 
* It provides fast and efficient operations on ndarrays
* NumPy operations perform complex computations on entire arrays without the need for Python "for" loops

In this Notebook I have covered Creation of Numpy array 1D, 2D, accessing elelemnst of Numpy array, 
Aggregate functions along Axis (i.e. rows or columns)

In [1]:
# import library
import numpy as np

In [2]:
np.__version__

'1.18.1'

### One dimensional array

In [3]:
# creating numpy array from tuple
tup = (1, 2, 3)

arr_tup = np.array(tup)

arr_tup

array([1, 2, 3])

In [4]:
type(arr_tup)

numpy.ndarray

In [5]:
# creating numpy array from a list
even = [2, 4, 6, 8, 10]

arr_even = np.array(even)
arr_even

array([ 2,  4,  6,  8, 10])

In [6]:
type(arr_even)

numpy.ndarray

In [7]:
arr_even.dtype

dtype('int32')

In [8]:
# Specify datatype at time of creation
odd = [1, 3, 5, 7]

arr_odd = np.array(odd, dtype='float')

arr_odd

array([1., 3., 5., 7.])

In [9]:
arr_odd.dtype

dtype('float64')

In [10]:
# Check no. of dimensions
# In NumPy dimensions are called axes.

print(arr_odd.ndim)

1


In [11]:
# shape of array 

print(arr_odd.shape)

(4,)


In [12]:
# Create array using np.arange

arr = np.arange(start=10, stop=20, step=2 )
print(arr)

[10 12 14 16 18]


In [13]:
# access elements of numpy array

print(arr[1]) # element at index 1

print(arr[0:5]) # elemets from index 0 to 4

print(arr[0:5:2]) # elements from index 0 to 4 at jump of 2


12
[10 12 14 16 18]
[10 14 18]


### Two dimensional array

In [14]:
list_of_lists = [[1,2,3],
                 [4,5,6],
                 [7,8,9]]

arr_2dim = np.array(list_of_lists)
arr_2dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# Check dimensions

arr_2dim.ndim

2

In [16]:
# Check shape

arr_2dim.shape

(3, 3)

In [17]:
# Create a 2d array
arr2d = np.arange(1, 13).reshape((3,4))
print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
arr2d.ndim

2

In [19]:
arr2d.shape

(3, 4)

In [20]:
## Access elements

# array[index of axis-0, index of axis-1]
print(arr2d[1, 1])

6


In [21]:
# access all elements of row at index 2
 arr2d[2]

array([ 9, 10, 11, 12])

In [22]:
arr2d[2, :]

array([ 9, 10, 11, 12])

In [23]:
# access all elements of col ar index 1
arr2d[:, 1]

array([ 2,  6, 10])

### Sum along axis

In [24]:
print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
arr2d.shape

(3, 4)

In [26]:
# Sum along axis 0
print(np.sum(arr2d, axis=0))

[15 18 21 24]


In [27]:
arr2d[0] 

array([1, 2, 3, 4])

In [28]:
arr2d[1]

array([5, 6, 7, 8])

In [29]:
arr2d[2]

array([ 9, 10, 11, 12])

In [30]:
# Sum along axis 1

np.sum(arr2d, axis=1)

array([10, 26, 42])

In [31]:
arr2d[:, 0]

array([1, 5, 9])

In [32]:
arr2d[:,1]

array([ 2,  6, 10])

In [33]:
arr2d[:, 2]

array([ 3,  7, 11])

In [34]:
arr2d[:, 3]

array([ 4,  8, 12])