In [2]:
import numpy as np

### In this notebook following topics are covered
* Create arrays with values initialized,
* Sort elements of arrays along axis
* Structured arrays
* Access elements of array based on logical conditions
* Aggregate functions
* Broadcasting

### We can create arrays initialized with values

In [3]:
# create one-dimensional array initialized with zero
np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
# create two dimensional array initialized with zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
# create one dimensional array initialized with ones
np.ones(3, dtype='int')

array([1, 1, 1])

In [6]:
# two dimensional array initialized with ones
np.ones((2,3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

### Sort elements of array

In [7]:
# Sort elements of array

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
# Sort elements of given axis
arr2d = np.array([[7, 9, 5],
                  [10, 19, 8],
                 [6, 21, 3]])
print(arr2d)

[[ 7  9  5]
 [10 19  8]
 [ 6 21  3]]


In [9]:
# Sort on basis of axis 0 
np.sort(arr2d, axis=0)

array([[ 6,  9,  3],
       [ 7, 19,  5],
       [10, 21,  8]])

In [10]:
# Sort on basis of axis 1
np.sort(arr2d, axis=1)

array([[ 5,  7,  9],
       [ 8, 10, 19],
       [ 3,  6, 21]])

In [11]:
# A structured array 

data =[('Ram', 33, 'M'), ('Karan', 28, 'F'), ('Vijay', 40, 'M')]

datatype = {'names'  :('name', 'age', 'gender'),
            'formats':('<U10', int, '<U1')}

arr_data = np.array(data, dtype=datatype)

print(arr_data)

[('Ram', 33, 'M') ('Karan', 28, 'F') ('Vijay', 40, 'M')]


In [12]:
# sort array based on age
np.sort(arr_data, order='age')

array([('Karan', 28, 'F'), ('Ram', 33, 'M'), ('Vijay', 40, 'M')],
      dtype=[('name', '<U10'), ('age', '<i4'), ('gender', '<U1')])

In [13]:
# sort array based on name
np.sort(arr_data, order='name')

array([('Karan', 28, 'F'), ('Ram', 33, 'M'), ('Vijay', 40, 'M')],
      dtype=[('name', '<U10'), ('age', '<i4'), ('gender', '<U1')])

In [14]:
# conditional access
arr_data[arr_data['age'] < 30]['name']

array(['Karan'], dtype='<U10')

### Aggregate Functions

In [15]:
# Compute sum of elements
arr = np.array([5, 7, 9, 4])

np.sum(arr)

25

In [16]:
# Compute mean 

np.mean(arr)

6.25

In [17]:
# Compute standard deviation
np.std(arr)

1.920286436967152

In [18]:
# Compute variance
np.var(arr)

3.6875

In [19]:
# Compute min
np.min(arr)

4

In [20]:
# Compute max
np.max(arr)

9

In [21]:
# Compute median
np.median(arr)

6.0

In [22]:
# Compute percentile - 25th
np.percentile(arr, 25)

4.75

In [23]:
# numpy.log() to calculate natural logarithmic value

np.log(12.2)

2.501435951739211

In [24]:
np.log10(100)

2.0

In [25]:
# custom base logb(x) = logc(x) / logc(b)

n= 1000
base=40

np.log(n)/np.log(base)

1.8725890517453545

## min, max on 2 dimension array

In [26]:
arr2d

array([[ 7,  9,  5],
       [10, 19,  8],
       [ 6, 21,  3]])

In [27]:
np.min(arr2d, axis=0), np.max(arr2d, axis=0)

(array([6, 9, 3]), array([10, 21,  8]))

In [28]:
np.min(arr2d, axis=1), np.max(arr2d, axis=1)

(array([5, 8, 3]), array([ 9, 19, 21]))

### Broadcasting

#### Rule 1: 
If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

#### Rule 2:
If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

#### Rule 3:
If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

<b>Example 1</b>

In [30]:
A = np.array([3,4,5])
B  = np.array([[1,2,3], [5,6,7]])

In [31]:
A.shape

(3,)

In [32]:
B.shape

(2, 3)

* A -> (1, 3) # Rule 1
* A -> (2, 3) # Rule 2

<b> Dimensions of A match with dimensions of B so addition is possible via boradcasting</b>

In [33]:
A+B

array([[ 4,  6,  8],
       [ 8, 10, 12]])

<b>Example 2</b>

In [34]:
A = np.array([[1,2], [3,4], [4,5]])
B = np.array([10, 20])

In [35]:
A.shape

(3, 2)

In [36]:
B.shape

(2,)

* B-> (1,2)
* B-> (3,2)

<b>Dimensions of B match with A so addition possible </b>

In [37]:
A+B

array([[11, 22],
       [13, 24],
       [14, 25]])

<b>Example 3</b>

In [38]:
A = np.array([1,2,3])
B = np.array([[10,11],[20,21]])


In [39]:
A.shape, B.shape

((3,), (2, 2))

* A - > (1,3) # Rule 1
* A - > (2,3) # Rule 2

<b> Dimensions of A and B don't match, so this will give error if we add</b>

In [8]:
A+B

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 